import Head from "next/head";
import { Inter } from "@next/font/google";
import Dedicated from "@/components/dedicated";
import Banner from "@/components/banner";
import Navbar from "@/components/navbar";
import Contact from "@/components/contact";
import Footers from "@/components/footers";
import Testimonials from "@/components/testimonials";
import Product from "@/components/product";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <Navbar />
      <Banner />
      <Dedicated />
      {/* new components */}
      <Product/>
      <Testimonials/>
      <Contact/>
      <Footers/>
    </>
  );
}
